import Node from "./node";

export default {
  nodes: [
    { id: "存储营销设备", label: "存储营销设备", cluster: "a", Class: Node },
    { id: "核心业务设施", label: "核心业务设施", cluster: "a", Class: Node },
    { id: "综合指标设施", label: "综合指标设施", cluster: "a", Class: Node },
    {
      id: "企业级客户信息设施",
      label: "企业级客户信息设施",
      cluster: "a",
      Class: Node,
    },
    {
      id: "移动发卡管理设施",
      label: "移动发卡管理设施",
      cluster: "a",
      Class: Node,
    },
    {
      id: "企业服务总线设施",
      label: "企业服务总线设施",
      cluster: "a",
      Class: Node,
    },
    { id: "统一付出设备", label: "统一付出设备", cluster: "a", Class: Node },
    {
      id: "贷后风险监测与预警设施",
      label: "贷后风险监测与预警设施",
      cluster: "a",
      Class: Node,
    },
    { id: "融合通信设备", label: "融合通信设备", cluster: "a", Class: Node },
    { id: "超级网络", label: "超级网络", cluster: "a", Class: Node },
    {
      id: "公务卡行内前置设施",
      label: "公务卡行内前置设施",
      cluster: "a",
      Class: Node,
    },
    { id: "App", label: "App", cluster: "a", Class: Node },
    { id: "自助智能设备", label: "自助智能设备", cluster: "a", Class: Node },
    { id: "中间业务设备", label: "中间业务设备", cluster: "a", Class: Node },
    {
      id: "财税库银前置设施",
      label: "财税库银前置设施",
      cluster: "a",
      Class: Node,
    },
    { id: "数字化设施", label: "数字化设施", cluster: "a", Class: Node },
    { id: "综合前置设施", label: "综合前置设施", cluster: "a", Class: Node },
    {
      id: "母子账户管理设施",
      label: "母子账户管理设施",
      cluster: "a",
      Class: Node,
    },
    {
      id: "公务卡银联数据前置设施",
      label: "公务卡银联数据前置设施",
      cluster: "a",
      Class: Node,
    },
    { id: "信贷管理设施", label: "信贷管理设施", cluster: "a", Class: Node },
    { id: "查控设备", label: "查控设备", cluster: "a", Class: Node },
    { id: "综合代销设施", label: "综合代销设施", cluster: "a", Class: Node },
    {
      id: "四川银政通信息服务设备",
      label: "四川银政通信息服务设备",
      cluster: "a",
      Class: Node,
    },
    { id: "函证管理设施", label: "函证管理设施", cluster: "a", Class: Node },
    {
      id: "信贷客户信息管理设施",
      label: "信贷客户信息管理设施",
      cluster: "a",
      Class: Node,
    },
    { id: "押品管理设施", label: "押品管理设施", cluster: "a", Class: Node },
    { id: "数字银行设施", label: "数字银行设施", cluster: "a", Class: Node },
    { id: "核心设施", label: "核心设施", cluster: "a", Class: Node },
    { id: "消息推送设备", label: "消息推送设备", cluster: "a", Class: Node },
    {
      id: "便捷助农终端设施",
      label: "便捷助农终端设施",
      cluster: "a",
      Class: Node,
    },
    { id: "青鸟消息设备", label: "青鸟消息设备", cluster: "a", Class: Node },
    { id: "联网核查设施", label: "联网核查设施", cluster: "a", Class: Node },
    { id: "金融IC卡设施", label: "金融IC卡设施", cluster: "a", Class: Node },
    { id: "智能排队设施", label: "智能排队设施", cluster: "a", Class: Node },
    { id: "积分设施", label: "积分设施", cluster: "a", Class: Node },
    {
      id: "理财发行管理设施",
      label: "理财发行管理设施",
      cluster: "a",
      Class: Node,
    },
    { id: "IC卡设施", label: "IC卡设施", cluster: "a", Class: Node },
    { id: "智能存储V2", label: "智能存储V2", cluster: "a", Class: Node },
    { id: "场景营销设备", label: "场景营销设备", cluster: "a", Class: Node },
    { id: "网联付出设施", label: "网联付出设施", cluster: "a", Class: Node },
    {
      id: "个人身份证联网核查设施",
      label: "个人身份证联网核查设施",
      cluster: "a",
      Class: Node,
    },
    {
      id: "企业账户管理设施",
      label: "企业账户管理设施",
      cluster: "a",
      Class: Node,
    },
    { id: "人脸识别设施", label: "人脸识别设施", cluster: "a", Class: Node },
    { id: "企业网络", label: "企业网络", cluster: "a", Class: Node },
    {
      id: "IFRS9估值与减值设施",
      label: "IFRS9估值与减值设施",
      cluster: "a",
      Class: Node,
    },
    {
      id: "国内信用证设施",
      label: "国内信用证设施",
      cluster: "a",
      Class: Node,
    },
    {
      id: "积分权益营销设备",
      label: "积分权益营销设备",
      cluster: "a",
      Class: Node,
    },
    { id: "社保激活APP", label: "社保激活APP", cluster: "a", Class: Node },
    {
      id: "财政代收代付业务设施",
      label: "财政代收代付业务设施",
      cluster: "a",
      Class: Node,
    },
    { id: "宜农POS设备", label: "宜农POS设备", cluster: "a", Class: Node },
    { id: "SGB设施", label: "SGB设施", cluster: "a", Class: Node },
    { id: "预算一体化", label: "预算一体化", cluster: "a", Class: Node },
    {
      id: "刷脸付前置设施",
      label: "刷脸付前置设施",
      cluster: "a",
      Class: Node,
    },
    {
      id: "统一集中账户管理设施",
      label: "统一集中账户管理设施",
      cluster: "a",
      Class: Node,
    },
    {
      id: "中间业务设备V2",
      label: "中间业务设备V2",
      cluster: "a",
      Class: Node,
    },
    {
      id: "银联二维码扫码付出前置设施",
      label: "银联二维码扫码付出前置设施",
      cluster: "a",
      Class: Node,
    },
    { id: "财务管理设施", label: "财务管理设施", cluster: "a", Class: Node },
    { id: "理财销售设施", label: "理财销售设施", cluster: "a", Class: Node },
    {
      id: "线上存储统计设备",
      label: "线上存储统计设备",
      cluster: "a",
      Class: Node,
    },
    { id: "电子验印设施", label: "电子验印设施", cluster: "a", Class: Node },
    {
      id: "代客资产管理设施",
      label: "代客资产管理设施",
      cluster: "a",
      Class: Node,
    },
    {
      id: "理财资产管理设施",
      label: "理财资产管理设施",
      cluster: "a",
      Class: Node,
    },
    {
      id: "新资金业务管理设施",
      label: "新资金业务管理设施",
      cluster: "a",
      Class: Node,
    },
    { id: "银企对账设施", label: "银企对账设施", cluster: "a", Class: Node },
    { id: "集中授权设施", label: "集中授权设施", cluster: "a", Class: Node },
    { id: "事后监督设施", label: "事后监督设施", cluster: "a", Class: Node },
    {
      id: "四川银联行业代付设备前置",
      label: "四川银联行业代付设备前置",
      cluster: "a",
      Class: Node,
    },
    { id: "网联前置", label: "网联前置", cluster: "a", Class: Node },
    { id: "新OA办公设施", label: "新OA办公设施", cluster: "a", Class: Node },
    {
      id: "四川政府债券前置",
      label: "四川政府债券前置",
      cluster: "a",
      Class: Node,
    },
    { id: "礼品派发设施", label: "礼品派发设施", cluster: "a", Class: Node },
  ],
  edges: [
    { source: "存储营销设备", target: "核心业务设施" },
    { source: "综合指标设施", target: "企业级客户信息设施" },
    { source: "移动发卡管理设施", target: "企业服务总线设施" },
    { source: "综合指标设施", target: "统一付出设备" },
    { source: "贷后风险监测与预警设施", target: "融合通信设备" },
    { source: "超级网络", target: "融合通信设备" },
    { source: "综合指标设施", target: "公务卡行内前置设施" },
    { source: "App", target: "公务卡行内前置设施" },
    { source: "综合指标设施", target: "核心业务设施" },
    { source: "自助智能设备", target: "核心业务设施" },
    { source: "综合指标设施", target: "中间业务设备" },
    { source: "自助智能设备", target: "融合通信设备" },
    { source: "财税库银前置设施", target: "数字化设施" },
    { source: "综合前置设施", target: "企业级客户信息设施" },
    { source: "综合前置设施", target: "核心业务设施" },
    { source: "App", target: "数字化设施" },
    { source: "App", target: "存储营销设备" },
    { source: "App", target: "统一付出设备" },
    { source: "中间业务设备", target: "母子账户管理设施" },
    { source: "App", target: "公务卡银联数据前置设施" },
    { source: "信贷管理设施", target: "融合通信设备" },
    { source: "查控设备", target: "综合代销设施" },
    { source: "综合指标设施", target: "存储营销设备" },
    { source: "统一付出设备", target: "四川银政通信息服务设备" },
    { source: "App", target: "核心业务设施" },
    { source: "函证管理设施", target: "融合通信设备" },
    { source: "中间业务设备", target: "信贷管理设施" },
    { source: "App", target: "企业级客户信息设施" },
    { source: "信贷客户信息管理设施", target: "企业级客户信息设施" },
    { source: "综合代销设施", target: "融合通信设备" },
    { source: "押品管理设施", target: "核心业务设施" },
    { source: "信贷管理设施", target: "押品管理设施" },
    { source: "App", target: "综合指标设施" },
    { source: "综合前置设施", target: "综合指标设施" },
    { source: "数字银行设施", target: "数字化设施" },
    { source: "综合指标设施", target: "核心设施" },
    { source: "函证管理设施", target: "核心业务设施" },
    { source: "函证管理设施", target: "消息推送设备" },
    { source: "存储营销设备", target: "融合通信设备" },
    { source: "便捷助农终端设施", target: "核心业务设施" },
    { source: "便捷助农终端设施", target: "青鸟消息设备" },
    { source: "便捷助农终端设施", target: "联网核查设施" },
    { source: "便捷助农终端设施", target: "企业级客户信息设施" },
    { source: "便捷助农终端设施", target: "金融IC卡设施" },
    { source: "便捷助农终端设施", target: "统一付出设备" },
    { source: "智能排队设施", target: "企业级客户信息设施" },
    { source: "智能排队设施", target: "核心设施" },
    { source: "企业级客户信息设施", target: "核心设施" },
    { source: "积分设施", target: "融合通信设备" },
    { source: "自助智能设备", target: "综合代销设施" },
    { source: "App", target: "融合通信设备" },
    { source: "理财发行管理设施", target: "融合通信设备" },
    { source: "App", target: "综合代销设施" },
    { source: "综合指标设施", target: "财税库银前置设施" },
    { source: "综合指标设施", target: "IC卡设施" },
    { source: "综合指标设施", target: "青鸟消息设备" },
    { source: "综合指标设施", target: "智能存储V2" },
    { source: "综合指标设施", target: "数字化设施" },
    { source: "综合指标设施", target: "企业服务总线设施" },
    { source: "场景营销设备", target: "企业级客户信息设施" },
    { source: "网联付出设施", target: "核心业务设施" },
    { source: "网联付出设施", target: "公务卡银联数据前置设施" },
    { source: "网联付出设施", target: "企业级客户信息设施" },
    { source: "网联付出设施", target: "融合通信设备" },
    { source: "综合指标设施", target: "个人身份证联网核查设施" },
    { source: "App", target: "智能排队设施" },
    { source: "积分设施", target: "企业级客户信息设施" },
    { source: "App", target: "信贷管理设施" },
    { source: "自助智能设备", target: "企业级客户信息设施" },
    { source: "自助智能设备", target: "IC卡设施" },
    { source: "自助智能设备", target: "核心设施" },
    { source: "自助智能设备", target: "个人身份证联网核查设施" },
    { source: "自助智能设备", target: "青鸟消息设备" },
    { source: "自助智能设备", target: "智能排队设施" },
    { source: "App", target: "中间业务设备" },
    { source: "企业账户管理设施", target: "综合指标设施" },
    { source: "企业账户管理设施", target: "核心业务设施" },
    { source: "移动发卡管理设施", target: "企业级客户信息设施" },
    { source: "移动发卡管理设施", target: "联网核查设施" },
    { source: "移动发卡管理设施", target: "融合通信设备" },
    { source: "移动发卡管理设施", target: "核心业务设施" },
    { source: "移动发卡管理设施", target: "金融IC卡设施" },
    { source: "移动发卡管理设施", target: "人脸识别设施" },
    { source: "综合指标设施", target: "企业网络" },
    { source: "核心业务设施", target: "融合通信设备" },
    { source: "数字化设施", target: "核心业务设施" },
    { source: "押品管理设施", target: "企业级客户信息设施" },
    { source: "押品管理设施", target: "信贷管理设施" },
    { source: "押品管理设施", target: "融合通信设备" },
    { source: "母子账户管理设施", target: "超级网络" },
    { source: "自助智能设备", target: "存储营销设备" },
    { source: "IFRS9估值与减值设施", target: "核心业务设施" },
    { source: "企业账户管理设施", target: "联网核查设施" },
    { source: "自助智能设备", target: "企业服务总线设施" },
    { source: "国内信用证设施", target: "核心业务设施" },
    { source: "四川银政通信息服务设备", target: "统一付出设备" },
    { source: "中间业务设备", target: "融合通信设备" },
    { source: "综合代销设施", target: "企业级客户信息设施" },
    { source: "统一付出设备", target: "网联付出设施" },
    { source: "国内信用证设施", target: "企业级客户信息设施" },
    { source: "超级网络", target: "核心业务设施" },
    { source: "积分权益营销设备", target: "青鸟消息设备" },
    { source: "综合指标设施", target: "公务卡银联数据前置设施" },
    { source: "统一付出设备", target: "融合通信设备" },
    { source: "社保激活APP", target: "企业级客户信息设施" },
    { source: "App", target: "智能存储V2" },
    { source: "网联付出设施", target: "统一付出设备" },
    { source: "四川银政通信息服务设备", target: "核心业务设施" },
    { source: "综合指标设施", target: "金融IC卡设施" },
    { source: "综合指标设施", target: "母子账户管理设施" },
    { source: "财政代收代付业务设施", target: "核心业务设施" },
    { source: "统一付出设备", target: "核心业务设施" },
    { source: "统一付出设备", target: "消息推送设备" },
    { source: "宜农POS设备", target: "智能存储V2" },
    { source: "财政代收代付业务设施", target: "统一付出设备" },
    { source: "宜农POS设备", target: "金融IC卡设施" },
    { source: "宜农POS设备", target: "核心业务设施" },
    { source: "积分设施", target: "核心业务设施" },
    { source: "积分设施", target: "消息推送设备" },
    { source: "查控设备", target: "统一付出设备" },
    { source: "综合指标设施", target: "融合通信设备" },
    { source: "SGB设施", target: "数字化设施" },
    { source: "预算一体化", target: "母子账户管理设施" },
    { source: "刷脸付前置设施", target: "核心业务设施" },
    { source: "存储营销设备", target: "企业级客户信息设施" },
    { source: "存储营销设备", target: "消息推送设备" },
    { source: "企业账户管理设施", target: "统一集中账户管理设施" },
    { source: "智能排队设施", target: "核心业务设施" },
    { source: "企业级客户信息设施", target: "核心业务设施" },
    { source: "联网核查设施", target: "综合指标设施" },
    { source: "中间业务设备V2", target: "核心业务设施" },
    { source: "企业账户管理设施", target: "企业级客户信息设施" },
    { source: "银联二维码扫码付出前置设施", target: "核心业务设施" },
    { source: "综合指标设施", target: "联网核查设施" },
    { source: "综合指标设施", target: "预算一体化" },
    { source: "预算一体化", target: "企业网络" },
    { source: "统一付出设备", target: "母子账户管理设施" },
    { source: "数字银行设施", target: "母子账户管理设施" },
    { source: "财务管理设施", target: "核心业务设施" },
    { source: "场景营销设备", target: "融合通信设备" },
    { source: "母子账户管理设施", target: "核心业务设施" },
    { source: "综合代销设施", target: "自助智能设备" },
    { source: "自助智能设备", target: "金融IC卡设施" },
    { source: "中间业务设备", target: "联网核查设施" },
    { source: "中间业务设备", target: "核心业务设施" },
    { source: "综合代销设施", target: "核心业务设施" },
    { source: "综合指标设施", target: "App" },
    { source: "中间业务设备", target: "统一付出设备" },
    { source: "数字银行设施", target: "统一付出设备" },
    { source: "数字银行设施", target: "超级网络" },
    { source: "App", target: "青鸟消息设备" },
    { source: "超级网络", target: "青鸟消息设备" },
    { source: "便捷助农终端设施", target: "企业服务总线设施" },
    { source: "便捷助农终端设施", target: "人脸识别设施" },
    { source: "自助智能设备", target: "理财销售设施" },
    { source: "综合指标设施", target: "综合代销设施" },
    { source: "综合代销设施", target: "统一付出设备" },
    { source: "线上存储统计设备", target: "消息推送设备" },
    { source: "统一付出设备", target: "公务卡银联数据前置设施" },
    { source: "自助智能设备", target: "人脸识别设施" },
    { source: "国内信用证设施", target: "信贷管理设施" },
    { source: "数字化设施", target: "融合通信设备" },
    { source: "数字银行设施", target: "函证管理设施" },
    { source: "核心业务设施", target: "企业级客户信息设施" },
    { source: "App", target: "超级网络" },
    { source: "企业账户管理设施", target: "个人身份证联网核查设施" },
    { source: "企业账户管理设施", target: "人脸识别设施" },
    { source: "四川银政通信息服务设备", target: "金融IC卡设施" },
    { source: "查控设备", target: "企业级客户信息设施" },
    { source: "电子验印设施", target: "核心业务设施" },
    { source: "代客资产管理设施", target: "统一付出设备" },
    { source: "综合指标设施", target: "人脸识别设施" },
    { source: "企业级客户信息设施", target: "融合通信设备" },
    { source: "理财资产管理设施", target: "融合通信设备" },
    { source: "超级网络", target: "公务卡行内前置设施" },
    { source: "超级网络", target: "公务卡银联数据前置设施" },
    { source: "App", target: "刷脸付前置设施" },
    { source: "App", target: "财政代收代付业务设施" },
    { source: "App", target: "人脸识别设施" },
    { source: "刷脸付前置设施", target: "统一付出设备" },
    { source: "App", target: "个人身份证联网核查设施" },
    { source: "统一付出设备", target: "超级网络" },
    { source: "存储营销设备", target: "自助智能设备" },
    { source: "财政代收代付业务设施", target: "企业网络" },
    { source: "综合指标设施", target: "财政代收代付业务设施" },
    { source: "预算一体化", target: "综合指标设施" },
    { source: "统一付出设备", target: "公务卡行内前置设施" },
    { source: "自助智能设备", target: "公务卡银联数据前置设施" },
    { source: "综合前置设施", target: "自助智能设备" },
    { source: "存储营销设备", target: "综合指标设施" },
    { source: "综合代销设施", target: "消息推送设备" },
    { source: "宜农POS设备", target: "存储营销设备" },
    { source: "自助智能设备", target: "统一付出设备" },
    { source: "母子账户管理设施", target: "统一付出设备" },
    { source: "母子账户管理设施", target: "青鸟消息设备" },
    { source: "财政代收代付业务设施", target: "综合指标设施" },
    { source: "数字银行设施", target: "财政代收代付业务设施" },
    { source: "自助智能设备", target: "联网核查设施" },
    { source: "预算一体化", target: "统一付出设备" },
    { source: "超级网络", target: "统一付出设备" },
    { source: "财务管理设施", target: "消息推送设备" },
    { source: "数字化设施", target: "企业级客户信息设施" },
    { source: "新资金业务管理设施", target: "核心业务设施" },
    { source: "企业级客户信息设施", target: "综合指标设施" },
    { source: "便捷助农终端设施", target: "融合通信设备" },
    { source: "数字银行设施", target: "银企对账设施" },
    { source: "App", target: "网联付出设施" },
    { source: "场景营销设备", target: "核心业务设施" },
    { source: "SGB设施", target: "企业级客户信息设施" },
    { source: "集中授权设施", target: "综合指标设施" },
    { source: "综合指标设施", target: "集中授权设施" },
    { source: "银企对账设施", target: "核心业务设施" },
    { source: "企业账户管理设施", target: "集中授权设施" },
    { source: "新资金业务管理设施", target: "统一付出设备" },
    { source: "App", target: "消息推送设备" },
    { source: "公务卡行内前置设施", target: "核心业务设施" },
    { source: "中间业务设备", target: "消息推送设备" },
    { source: "企业账户管理设施", target: "银企对账设施" },
    { source: "理财销售设施", target: "统一付出设备" },
    { source: "企业级客户信息设施", target: "自助智能设备" },
    { source: "综合代销设施", target: "综合指标设施" },
    { source: "场景营销设备", target: "消息推送设备" },
    { source: "智能排队设施", target: "App" },
    { source: "财务管理设施", target: "融合通信设备" },
    { source: "场景营销设备", target: "统一付出设备" },
    { source: "中间业务设备", target: "自助智能设备" },
    { source: "中间业务设备", target: "综合指标设施" },
    { source: "新资金业务管理设施", target: "企业级客户信息设施" },
    { source: "预算一体化", target: "核心业务设施" },
    { source: "App", target: "联网核查设施" },
    { source: "事后监督设施", target: "综合指标设施" },
    { source: "App", target: "理财销售设施" },
    { source: "综合代销设施", target: "理财销售设施" },
    { source: "集中授权设施", target: "核心业务设施" },
    { source: "综合指标设施", target: "超级网络" },
    { source: "统一付出设备", target: "预算一体化" },
    { source: "数字化设施", target: "统一付出设备" },
    { source: "数字银行设施", target: "企业级客户信息设施" },
    { source: "统一付出设备", target: "数字化设施" },
    { source: "预算一体化", target: "消息推送设备" },
    { source: "财税库银前置设施", target: "统一付出设备" },
    { source: "企业账户管理设施", target: "母子账户管理设施" },
    { source: "母子账户管理设施", target: "消息推送设备" },
    { source: "超级网络", target: "母子账户管理设施" },
    { source: "银企对账设施", target: "电子验印设施" },
    { source: "四川银联行业代付设备前置", target: "核心业务设施" },
    { source: "综合指标设施", target: "电子验印设施" },
    { source: "App", target: "网联前置" },
    { source: "IFRS9估值与减值设施", target: "消息推送设备" },
    { source: "四川银政通信息服务设备", target: "信贷管理设施" },
    { source: "统一付出设备", target: "中间业务设备" },
    { source: "数字化设施", target: "消息推送设备" },
    { source: "数字化设施", target: "青鸟消息设备" },
    { source: "新OA办公设施", target: "青鸟消息设备" },
    { source: "App", target: "企业服务总线设施" },
    { source: "四川政府债券前置", target: "消息推送设备" },
    { source: "礼品派发设施", target: "消息推送设备" },
  ],
};
