import Edge from "./edge";
import Node from "./node.js";
import Center from "./center";

export default {
  nodes: [
    {
      id: "存储营销设备",
      name: "存储营销设备",
      type: "main",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Center,
      degree: 3,
      size: 10,
    },
    {
      id: "核心业务设施",
      name: "核心业务设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "综合指标设施",
      name: "综合指标设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "企业级客户信息设施",
      name: "企业级客户信息设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "移动发卡管理设施",
      name: "移动发卡管理设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "企业服务总线设施",
      name: "企业服务总线设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "统一付出设备",
      name: "统一付出设备",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "贷后风险监测与预警设施",
      name: "贷后风险监测与预警设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "融合通信设备",
      name: "融合通信设备",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "超级网络",
      name: "超级网络",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "公务卡行内前置设施",
      name: "公务卡行内前置设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "App",
      name: "App",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "自助智能设备",
      name: "自助智能设备",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "中间业务设备",
      name: "中间业务设备",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "财税库银前置设施",
      name: "财税库银前置设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "数字化设施",
      name: "数字化设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "综合前置设施",
      name: "综合前置设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "母子账户管理设施",
      name: "母子账户管理设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "公务卡银联数据前置设施",
      name: "公务卡银联数据前置设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "信贷管理设施",
      name: "信贷管理设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "查控设备",
      name: "查控设备",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "综合代销设施",
      name: "综合代销设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "四川银政通信息服务设备",
      name: "四川银政通信息服务设备",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "函证管理设施",
      name: "函证管理设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "信贷客户信息管理设施",
      name: "信贷客户信息管理设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "押品管理设施",
      name: "押品管理设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "数字银行设施",
      name: "数字银行设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "核心设施",
      name: "核心设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "消息推送设备",
      name: "消息推送设备",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "便捷助农终端设施",
      name: "便捷助农终端设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "青鸟消息设备",
      name: "青鸟消息设备",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "联网核查设施",
      name: "联网核查设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "金融IC卡设施",
      name: "金融IC卡设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "智能排队设施",
      name: "智能排队设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "积分设施",
      name: "积分设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "理财发行管理设施",
      name: "理财发行管理设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "IC卡设施",
      name: "IC卡设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "智能存储V2",
      name: "智能存储V2",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "场景营销设备",
      name: "场景营销设备",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "网联付出设施",
      name: "网联付出设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "个人身份证联网核查设施",
      name: "个人身份证联网核查设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "企业账户管理设施",
      name: "企业账户管理设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "人脸识别设施",
      name: "人脸识别设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "企业网络",
      name: "企业网络",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "IFRS9估值与减值设施",
      name: "IFRS9估值与减值设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "国内信用证设施",
      name: "国内信用证设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "积分权益营销设备",
      name: "积分权益营销设备",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "社保激活APP",
      name: "社保激活APP",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "财政代收代付业务设施",
      name: "财政代收代付业务设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "宜农POS设备",
      name: "宜农POS设备",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "SGB设施",
      name: "SGB设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "预算一体化",
      name: "预算一体化",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "刷脸付前置设施",
      name: "刷脸付前置设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "统一集中账户管理设施",
      name: "统一集中账户管理设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "中间业务设备V2",
      name: "中间业务设备V2",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "银联二维码扫码付出前置设施",
      name: "银联二维码扫码付出前置设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "财务管理设施",
      name: "财务管理设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "理财销售设施",
      name: "理财销售设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "线上存储统计设备",
      name: "线上存储统计设备",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "电子验印设施",
      name: "电子验印设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "代客资产管理设施",
      name: "代客资产管理设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "理财资产管理设施",
      name: "理财资产管理设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "新资金业务管理设施",
      name: "新资金业务管理设施",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "银企对账设施",
      name: "银企对账设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "集中授权设施",
      name: "集中授权设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "事后监督设施",
      name: "事后监督设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "四川银联行业代付设备前置",
      name: "四川银联行业代付设备前置",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "网联前置",
      name: "网联前置",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "新OA办公设施",
      name: "新OA办公设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "四川政府债券前置",
      name: "四川政府债券前置",

      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
    {
      id: "礼品派发设施",
      name: "礼品派发设施",
      type: "prop",
      iconType: "iconapplication",
      className: "icon-background",
      Class: Node,
      degree: 3,
      size: 10,
    },
  ],
  edges: [
    { Class: Edge, source: "存储营销设备", target: "核心业务设施" },
    { Class: Edge, source: "综合指标设施", target: "企业级客户信息设施" },
    { Class: Edge, source: "移动发卡管理设施", target: "企业服务总线设施" },
    { Class: Edge, source: "综合指标设施", target: "统一付出设备" },
    { Class: Edge, source: "贷后风险监测与预警设施", target: "融合通信设备" },
    { Class: Edge, source: "超级网络", target: "融合通信设备" },
    { Class: Edge, source: "综合指标设施", target: "公务卡行内前置设施" },
    { Class: Edge, source: "App", target: "公务卡行内前置设施" },
    { Class: Edge, source: "综合指标设施", target: "核心业务设施" },
    { Class: Edge, source: "自助智能设备", target: "核心业务设施" },
    { Class: Edge, source: "综合指标设施", target: "中间业务设备" },
    { Class: Edge, source: "自助智能设备", target: "融合通信设备" },
    { Class: Edge, source: "财税库银前置设施", target: "数字化设施" },
    { Class: Edge, source: "综合前置设施", target: "企业级客户信息设施" },
    { Class: Edge, source: "综合前置设施", target: "核心业务设施" },
    { Class: Edge, source: "App", target: "数字化设施" },
    { Class: Edge, source: "App", target: "存储营销设备" },
    { Class: Edge, source: "App", target: "统一付出设备" },
    { Class: Edge, source: "中间业务设备", target: "母子账户管理设施" },
    { Class: Edge, source: "App", target: "公务卡银联数据前置设施" },
    { Class: Edge, source: "信贷管理设施", target: "融合通信设备" },
    { Class: Edge, source: "查控设备", target: "综合代销设施" },
    { Class: Edge, source: "综合指标设施", target: "存储营销设备" },
    { Class: Edge, source: "统一付出设备", target: "四川银政通信息服务设备" },
    { Class: Edge, source: "App", target: "核心业务设施" },
    { Class: Edge, source: "函证管理设施", target: "融合通信设备" },
    { Class: Edge, source: "中间业务设备", target: "信贷管理设施" },
    { Class: Edge, source: "App", target: "企业级客户信息设施" },
    {
      Class: Edge,
      source: "信贷客户信息管理设施",
      target: "企业级客户信息设施",
    },
    { Class: Edge, source: "综合代销设施", target: "融合通信设备" },
    { Class: Edge, source: "押品管理设施", target: "核心业务设施" },
    { Class: Edge, source: "信贷管理设施", target: "押品管理设施" },
    { Class: Edge, source: "App", target: "综合指标设施" },
    { Class: Edge, source: "综合前置设施", target: "综合指标设施" },
    { Class: Edge, source: "数字银行设施", target: "数字化设施" },
    { Class: Edge, source: "综合指标设施", target: "核心设施" },
    { Class: Edge, source: "函证管理设施", target: "核心业务设施" },
    { Class: Edge, source: "函证管理设施", target: "消息推送设备" },
    { Class: Edge, source: "存储营销设备", target: "融合通信设备" },
    { Class: Edge, source: "便捷助农终端设施", target: "核心业务设施" },
    { Class: Edge, source: "便捷助农终端设施", target: "青鸟消息设备" },
    { Class: Edge, source: "便捷助农终端设施", target: "联网核查设施" },
    { Class: Edge, source: "便捷助农终端设施", target: "企业级客户信息设施" },
    { Class: Edge, source: "便捷助农终端设施", target: "金融IC卡设施" },
    { Class: Edge, source: "便捷助农终端设施", target: "统一付出设备" },
    { Class: Edge, source: "智能排队设施", target: "企业级客户信息设施" },
    { Class: Edge, source: "智能排队设施", target: "核心设施" },
    { Class: Edge, source: "企业级客户信息设施", target: "核心设施" },
    { Class: Edge, source: "积分设施", target: "融合通信设备" },
    { Class: Edge, source: "自助智能设备", target: "综合代销设施" },
    { Class: Edge, source: "App", target: "融合通信设备" },
    { Class: Edge, source: "理财发行管理设施", target: "融合通信设备" },
    { Class: Edge, source: "App", target: "综合代销设施" },
    { Class: Edge, source: "综合指标设施", target: "财税库银前置设施" },
    { Class: Edge, source: "综合指标设施", target: "IC卡设施" },
    { Class: Edge, source: "综合指标设施", target: "青鸟消息设备" },
    { Class: Edge, source: "综合指标设施", target: "智能存储V2" },
    { Class: Edge, source: "综合指标设施", target: "数字化设施" },
    { Class: Edge, source: "综合指标设施", target: "企业服务总线设施" },
    { Class: Edge, source: "场景营销设备", target: "企业级客户信息设施" },
    { Class: Edge, source: "网联付出设施", target: "核心业务设施" },
    { Class: Edge, source: "网联付出设施", target: "公务卡银联数据前置设施" },
    { Class: Edge, source: "网联付出设施", target: "企业级客户信息设施" },
    { Class: Edge, source: "网联付出设施", target: "融合通信设备" },
    { Class: Edge, source: "综合指标设施", target: "个人身份证联网核查设施" },
    { Class: Edge, source: "App", target: "智能排队设施" },
    { Class: Edge, source: "积分设施", target: "企业级客户信息设施" },
    { Class: Edge, source: "App", target: "信贷管理设施" },
    { Class: Edge, source: "自助智能设备", target: "企业级客户信息设施" },
    { Class: Edge, source: "自助智能设备", target: "IC卡设施" },
    { Class: Edge, source: "自助智能设备", target: "核心设施" },
    { Class: Edge, source: "自助智能设备", target: "个人身份证联网核查设施" },
    { Class: Edge, source: "自助智能设备", target: "青鸟消息设备" },
    { Class: Edge, source: "自助智能设备", target: "智能排队设施" },
    { Class: Edge, source: "App", target: "中间业务设备" },
    { Class: Edge, source: "企业账户管理设施", target: "综合指标设施" },
    { Class: Edge, source: "企业账户管理设施", target: "核心业务设施" },
    { Class: Edge, source: "移动发卡管理设施", target: "企业级客户信息设施" },
    { Class: Edge, source: "移动发卡管理设施", target: "联网核查设施" },
    { Class: Edge, source: "移动发卡管理设施", target: "融合通信设备" },
    { Class: Edge, source: "移动发卡管理设施", target: "核心业务设施" },
    { Class: Edge, source: "移动发卡管理设施", target: "金融IC卡设施" },
    { Class: Edge, source: "移动发卡管理设施", target: "人脸识别设施" },
    { Class: Edge, source: "综合指标设施", target: "企业网络" },
    { Class: Edge, source: "核心业务设施", target: "融合通信设备" },
    { Class: Edge, source: "数字化设施", target: "核心业务设施" },
    { Class: Edge, source: "押品管理设施", target: "企业级客户信息设施" },
    { Class: Edge, source: "押品管理设施", target: "信贷管理设施" },
    { Class: Edge, source: "押品管理设施", target: "融合通信设备" },
    { Class: Edge, source: "母子账户管理设施", target: "超级网络" },
    { Class: Edge, source: "自助智能设备", target: "存储营销设备" },
    { Class: Edge, source: "IFRS9估值与减值设施", target: "核心业务设施" },
    { Class: Edge, source: "企业账户管理设施", target: "联网核查设施" },
    { Class: Edge, source: "自助智能设备", target: "企业服务总线设施" },
    { Class: Edge, source: "国内信用证设施", target: "核心业务设施" },
    { Class: Edge, source: "四川银政通信息服务设备", target: "统一付出设备" },
    { Class: Edge, source: "中间业务设备", target: "融合通信设备" },
    { Class: Edge, source: "综合代销设施", target: "企业级客户信息设施" },
    { Class: Edge, source: "统一付出设备", target: "网联付出设施" },
    { Class: Edge, source: "国内信用证设施", target: "企业级客户信息设施" },
    { Class: Edge, source: "超级网络", target: "核心业务设施" },
    { Class: Edge, source: "积分权益营销设备", target: "青鸟消息设备" },
    { Class: Edge, source: "综合指标设施", target: "公务卡银联数据前置设施" },
    { Class: Edge, source: "统一付出设备", target: "融合通信设备" },
    { Class: Edge, source: "社保激活APP", target: "企业级客户信息设施" },
    { Class: Edge, source: "App", target: "智能存储V2" },
    { Class: Edge, source: "网联付出设施", target: "统一付出设备" },
    { Class: Edge, source: "四川银政通信息服务设备", target: "核心业务设施" },
    { Class: Edge, source: "综合指标设施", target: "金融IC卡设施" },
    { Class: Edge, source: "综合指标设施", target: "母子账户管理设施" },
    { Class: Edge, source: "财政代收代付业务设施", target: "核心业务设施" },
    { Class: Edge, source: "统一付出设备", target: "核心业务设施" },
    { Class: Edge, source: "统一付出设备", target: "消息推送设备" },
    { Class: Edge, source: "宜农POS设备", target: "智能存储V2" },
    { Class: Edge, source: "财政代收代付业务设施", target: "统一付出设备" },
    { Class: Edge, source: "宜农POS设备", target: "金融IC卡设施" },
    { Class: Edge, source: "宜农POS设备", target: "核心业务设施" },
    { Class: Edge, source: "积分设施", target: "核心业务设施" },
    { Class: Edge, source: "积分设施", target: "消息推送设备" },
    { Class: Edge, source: "查控设备", target: "统一付出设备" },
    { Class: Edge, source: "综合指标设施", target: "融合通信设备" },
    { Class: Edge, source: "SGB设施", target: "数字化设施" },
    { Class: Edge, source: "预算一体化", target: "母子账户管理设施" },
    { Class: Edge, source: "刷脸付前置设施", target: "核心业务设施" },
    { Class: Edge, source: "存储营销设备", target: "企业级客户信息设施" },
    { Class: Edge, source: "存储营销设备", target: "消息推送设备" },
    { Class: Edge, source: "企业账户管理设施", target: "统一集中账户管理设施" },
    { Class: Edge, source: "智能排队设施", target: "核心业务设施" },
    { Class: Edge, source: "企业级客户信息设施", target: "核心业务设施" },
    { Class: Edge, source: "联网核查设施", target: "综合指标设施" },
    { Class: Edge, source: "中间业务设备V2", target: "核心业务设施" },
    { Class: Edge, source: "企业账户管理设施", target: "企业级客户信息设施" },
    {
      Class: Edge,
      source: "银联二维码扫码付出前置设施",
      target: "核心业务设施",
    },
    { Class: Edge, source: "综合指标设施", target: "联网核查设施" },
    { Class: Edge, source: "综合指标设施", target: "预算一体化" },
    { Class: Edge, source: "预算一体化", target: "企业网络" },
    { Class: Edge, source: "统一付出设备", target: "母子账户管理设施" },
    { Class: Edge, source: "数字银行设施", target: "母子账户管理设施" },
    { Class: Edge, source: "财务管理设施", target: "核心业务设施" },
    { Class: Edge, source: "场景营销设备", target: "融合通信设备" },
    { Class: Edge, source: "母子账户管理设施", target: "核心业务设施" },
    { Class: Edge, source: "综合代销设施", target: "自助智能设备" },
    { Class: Edge, source: "自助智能设备", target: "金融IC卡设施" },
    { Class: Edge, source: "中间业务设备", target: "联网核查设施" },
    { Class: Edge, source: "中间业务设备", target: "核心业务设施" },
    { Class: Edge, source: "综合代销设施", target: "核心业务设施" },
    { Class: Edge, source: "综合指标设施", target: "App" },
    { Class: Edge, source: "中间业务设备", target: "统一付出设备" },
    { Class: Edge, source: "数字银行设施", target: "统一付出设备" },
    { Class: Edge, source: "数字银行设施", target: "超级网络" },
    { Class: Edge, source: "App", target: "青鸟消息设备" },
    { Class: Edge, source: "超级网络", target: "青鸟消息设备" },
    { Class: Edge, source: "便捷助农终端设施", target: "企业服务总线设施" },
    { Class: Edge, source: "便捷助农终端设施", target: "人脸识别设施" },
    { Class: Edge, source: "自助智能设备", target: "理财销售设施" },
    { Class: Edge, source: "综合指标设施", target: "综合代销设施" },
    { Class: Edge, source: "综合代销设施", target: "统一付出设备" },
    { Class: Edge, source: "线上存储统计设备", target: "消息推送设备" },
    { Class: Edge, source: "统一付出设备", target: "公务卡银联数据前置设施" },
    { Class: Edge, source: "自助智能设备", target: "人脸识别设施" },
    { Class: Edge, source: "国内信用证设施", target: "信贷管理设施" },
    { Class: Edge, source: "数字化设施", target: "融合通信设备" },
    { Class: Edge, source: "数字银行设施", target: "函证管理设施" },
    { Class: Edge, source: "核心业务设施", target: "企业级客户信息设施" },
    { Class: Edge, source: "App", target: "超级网络" },
    {
      Class: Edge,
      source: "企业账户管理设施",
      target: "个人身份证联网核查设施",
    },
    { Class: Edge, source: "企业账户管理设施", target: "人脸识别设施" },
    { Class: Edge, source: "四川银政通信息服务设备", target: "金融IC卡设施" },
    { Class: Edge, source: "查控设备", target: "企业级客户信息设施" },
    { Class: Edge, source: "电子验印设施", target: "核心业务设施" },
    { Class: Edge, source: "代客资产管理设施", target: "统一付出设备" },
    { Class: Edge, source: "综合指标设施", target: "人脸识别设施" },
    { Class: Edge, source: "企业级客户信息设施", target: "融合通信设备" },
    { Class: Edge, source: "理财资产管理设施", target: "融合通信设备" },
    { Class: Edge, source: "超级网络", target: "公务卡行内前置设施" },
    { Class: Edge, source: "超级网络", target: "公务卡银联数据前置设施" },
    { Class: Edge, source: "App", target: "刷脸付前置设施" },
    { Class: Edge, source: "App", target: "财政代收代付业务设施" },
    { Class: Edge, source: "App", target: "人脸识别设施" },
    { Class: Edge, source: "刷脸付前置设施", target: "统一付出设备" },
    { Class: Edge, source: "App", target: "个人身份证联网核查设施" },
    { Class: Edge, source: "统一付出设备", target: "超级网络" },
    { Class: Edge, source: "存储营销设备", target: "自助智能设备" },
    { Class: Edge, source: "财政代收代付业务设施", target: "企业网络" },
    { Class: Edge, source: "综合指标设施", target: "财政代收代付业务设施" },
    { Class: Edge, source: "预算一体化", target: "综合指标设施" },
    { Class: Edge, source: "统一付出设备", target: "公务卡行内前置设施" },
    { Class: Edge, source: "自助智能设备", target: "公务卡银联数据前置设施" },
    { Class: Edge, source: "综合前置设施", target: "自助智能设备" },
    { Class: Edge, source: "存储营销设备", target: "综合指标设施" },
    { Class: Edge, source: "综合代销设施", target: "消息推送设备" },
    { Class: Edge, source: "宜农POS设备", target: "存储营销设备" },
    { Class: Edge, source: "自助智能设备", target: "统一付出设备" },
    { Class: Edge, source: "母子账户管理设施", target: "统一付出设备" },
    { Class: Edge, source: "母子账户管理设施", target: "青鸟消息设备" },
    { Class: Edge, source: "财政代收代付业务设施", target: "综合指标设施" },
    { Class: Edge, source: "数字银行设施", target: "财政代收代付业务设施" },
    { Class: Edge, source: "自助智能设备", target: "联网核查设施" },
    { Class: Edge, source: "预算一体化", target: "统一付出设备" },
    { Class: Edge, source: "超级网络", target: "统一付出设备" },
    { Class: Edge, source: "财务管理设施", target: "消息推送设备" },
    { Class: Edge, source: "数字化设施", target: "企业级客户信息设施" },
    { Class: Edge, source: "新资金业务管理设施", target: "核心业务设施" },
    { Class: Edge, source: "企业级客户信息设施", target: "综合指标设施" },
    { Class: Edge, source: "便捷助农终端设施", target: "融合通信设备" },
    { Class: Edge, source: "数字银行设施", target: "银企对账设施" },
    { Class: Edge, source: "App", target: "网联付出设施" },
    { Class: Edge, source: "场景营销设备", target: "核心业务设施" },
    { Class: Edge, source: "SGB设施", target: "企业级客户信息设施" },
    { Class: Edge, source: "集中授权设施", target: "综合指标设施" },
    { Class: Edge, source: "综合指标设施", target: "集中授权设施" },
    { Class: Edge, source: "银企对账设施", target: "核心业务设施" },
    { Class: Edge, source: "企业账户管理设施", target: "集中授权设施" },
    { Class: Edge, source: "新资金业务管理设施", target: "统一付出设备" },
    { Class: Edge, source: "App", target: "消息推送设备" },
    { Class: Edge, source: "公务卡行内前置设施", target: "核心业务设施" },
    { Class: Edge, source: "中间业务设备", target: "消息推送设备" },
    { Class: Edge, source: "企业账户管理设施", target: "银企对账设施" },
    { Class: Edge, source: "理财销售设施", target: "统一付出设备" },
    { Class: Edge, source: "企业级客户信息设施", target: "自助智能设备" },
    { Class: Edge, source: "综合代销设施", target: "综合指标设施" },
    { Class: Edge, source: "场景营销设备", target: "消息推送设备" },
    { Class: Edge, source: "智能排队设施", target: "App" },
    { Class: Edge, source: "财务管理设施", target: "融合通信设备" },
    { Class: Edge, source: "场景营销设备", target: "统一付出设备" },
    { Class: Edge, source: "中间业务设备", target: "自助智能设备" },
    { Class: Edge, source: "中间业务设备", target: "综合指标设施" },
    { Class: Edge, source: "新资金业务管理设施", target: "企业级客户信息设施" },
    { Class: Edge, source: "预算一体化", target: "核心业务设施" },
    { Class: Edge, source: "App", target: "联网核查设施" },
    { Class: Edge, source: "事后监督设施", target: "综合指标设施" },
    { Class: Edge, source: "App", target: "理财销售设施" },
    { Class: Edge, source: "综合代销设施", target: "理财销售设施" },
    { Class: Edge, source: "集中授权设施", target: "核心业务设施" },
    { Class: Edge, source: "综合指标设施", target: "超级网络" },
    { Class: Edge, source: "统一付出设备", target: "预算一体化" },
    { Class: Edge, source: "数字化设施", target: "统一付出设备" },
    { Class: Edge, source: "数字银行设施", target: "企业级客户信息设施" },
    { Class: Edge, source: "统一付出设备", target: "数字化设施" },
    { Class: Edge, source: "预算一体化", target: "消息推送设备" },
    { Class: Edge, source: "财税库银前置设施", target: "统一付出设备" },
    { Class: Edge, source: "企业账户管理设施", target: "母子账户管理设施" },
    { Class: Edge, source: "母子账户管理设施", target: "消息推送设备" },
    { Class: Edge, source: "超级网络", target: "母子账户管理设施" },
    { Class: Edge, source: "银企对账设施", target: "电子验印设施" },
    { Class: Edge, source: "四川银联行业代付设备前置", target: "核心业务设施" },
    { Class: Edge, source: "综合指标设施", target: "电子验印设施" },
    { Class: Edge, source: "App", target: "网联前置" },
    { Class: Edge, source: "IFRS9估值与减值设施", target: "消息推送设备" },
    { Class: Edge, source: "四川银政通信息服务设备", target: "信贷管理设施" },
    { Class: Edge, source: "统一付出设备", target: "中间业务设备" },
    { Class: Edge, source: "数字化设施", target: "消息推送设备" },
    { Class: Edge, source: "数字化设施", target: "青鸟消息设备" },
    { Class: Edge, source: "新OA办公设施", target: "青鸟消息设备" },
    { Class: Edge, source: "App", target: "企业服务总线设施" },
    { Class: Edge, source: "四川政府债券前置", target: "消息推送设备" },
    { Class: Edge, source: "礼品派发设施", target: "消息推送设备" },
  ],
};
